FROM nginx:1.25.3
LABEL maintainer="jess@mintopia.net"

COPY nginx.conf /etc/nginx/templates/nginx.conf.template
COPY default.conf /etc/nginx/templates/conf.d/default.conf.template

ENV \
    STATUS_ALLOW=127.0.0.1 \
    NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
