version: '3'
name: php-docker
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./public:/var/www/public
    ports:
      - 8100:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile.php-fpm
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./public:/var/www/public